version: 2.1
orbs:
  continuation: circleci/continuation@0.5.0

# This allows you to use CircleCI's dynamic configuration feature
setup: true

workflows:
  run-filter:
    jobs:
      - continuation/continue:
          configuration_path: ".circleci/dynamic_config.yml"
          parameters: '{"run-frontend":true, "run-backend" : true}'
