name: "backend-test"

on:
  workflow_dispatch:

jobs:
  frontend-test:
    name: "frontend-test"
    runs-on:
    - "ubuntu-latest"
    container:
      image: "cimg/node:15.1"
    steps:
    - uses: "actions/checkout@v4"
    - run: "npm install"
    - 
      run: "npm test"
      name: "Run tests"
