name: Vue



on: [ push ]



jobs:
 path-filtering-filter:
  
  runs-on: ubuntu-latest
  
  steps:
   - name: Base
     run:  base-revision  main 
   - name: Run frontend and backend
     run: |
      frontend/.* run-frontend true  
      backend/.* run-backend true 
   - name: Config path
     run: config-path  ".circleci/dynamic_config.yml" 
