name: "backend-test"

on:
  workflow_dispatch:

jobs:
  backend-test:
    name: "backend-test"
    runs-on:
    - "ubuntu-latest"
    container:
      image: "cimg/python:3.8"
    steps:
    - uses: "actions/checkout@v4"
    - run: "pip install -r requirements.txt"
    - 
      run: "pytest"
      name: "Run tests"
